[tool.docformatter]
in-place = true
recursive = true
wrap-summaries = 88
wrap-descriptions = 81

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203"]

[tool.flake8.known-modules]
"" = ["devsync"]

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.pylint.BASIC]
# Stick to snake case, but accept setUp and tearDown from unittest
method-rgx = "(([a-z_][a-z0-9_]*)|(setUp)|(tearDown))$"

[tool.pylint.FORMAT]
max-line-length = 120

[tool.pylint.MASTER]
# Add files or directories to the blacklist. They should be base names, not paths.
ignore = ["venv"]

[tool.pylint."MESSAGES CONTROL"]
# Only show warnings with the listed confidence levels. Leave empty to show
# all. Valid levels: HIGH, INFERENCE, INFERENCE_FAILURE, UNDEFINED
confidence = ""
disable = [
  "missing-function-docstring",
  "missing-class-docstring",
  "missing-module-docstring",
  "import-error", # disabled since pre-commit runs pylint in a separate venv
  "unspecified-encoding",
  "fixme",
  "too-few-public-methods",
  "no-name-in-module"
]

[tool.ruff]
fix = true
line-length = 120
target-version = "py310"
select = ["ALL"]
ignore = [
  "ANN",
  "ARG",
  "COM", # Done via black
  "D",
  "FBT",
  "FIX",
  "I", # Done via isort
  "PT", # TODO convert to pytest
  "S", # TODO resolve after pytest conversion
  "T",
  "TD"
]
